In [1]:
import pandas as pd
import requests

C:\Users\met.officer4\AppData\Local\Temp\ipykernel_8012\1058106858.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
response = requests.get('http://itgfscn2z1:38772/tdamr/service_get_masdreg_cinf.jsp?handshake=cHPo7dbRyoc0wrxs2Luc9SD1a30ji01s67a')

In [2]:
df = pd.DataFrame()

In [7]:
if response.status_code == 200:
    response = requests.get('http://itgfscn2z1:38772/tdamr/service_get_masdreg_cinf.jsp?handshake=cHPo7dbRyoc0wrxs2Luc9SD1a30ji01s67a')
    temp_df = pd.DataFrame(response.json()[0]['DATA']) 
else:
    print('Error', response.status_code)

In [10]:
temp_df

,STA,NA3,NA4,NA5,NA2,NA1,PIN,EN1,EN2,CONS_NUM,NA6
0,C,"MANI SQUARE,IT 9TH FLOOR","164/1,MANIKTALA MAIN ROAD",KOLKATA,PVT LTD,M/S FABWORTH PROMOTERS,700054,M/S FABWORTH PROMOTERS,PVT LTD,0104101301,NaN
1,L,"A-1,NEW ALIPORE",KOLKATA,NaN,SERVICES PRIVATE LTD,M/S BHATTASALI PRINT &,700053,BHATTASALI PRINT &,SERVICES PRIVATE LTD,0101000801,NaN
2,L,TURNER MORRISON BLDG,"6,LYONS RANGE",1ST FLOOR,LIMITED,M/S TURNER MORRISON,700001,CALCUTTA STOCK EXCHANGE,NO-2,0103301101,KOLKATA
3,L,PUBLIC WORKS DEPARTMENT,"3RD FL.RM.NO-310&308,OF KHADYA BHAWAN,","BL.-A,11A,MIRZA GHALIB STREET",DEPUTY SECRETARY,ACCOUNTS OFFICER & EX-OFFICIO,700087,GOVT. OF WEST BENGAL,WRITERS' BUILDINGS,0103301200,KOLKATA
4,L,"2ND FLOOR,BLOCK-C",NEW SECRETARIAT BUILDING,"1,KIRAN SANKAR ROY ROAD",KOLKATA WEST DIVISION,"THE EXECUTIVE ENGINEER, P.W.D",700001,NEW SECRETARIAT BLDG.,NaN,0105300400,KOLKATA
...,...,...,...,...,...,...,...,...,...,...,...
2880,L,"21,HEMANTA BASU SARANI",KOLKATA,NaN,ASSOCIATION,CENTER POINT OWNERS,700001,INDIA STEAMSHIP,NaN,0103501400,NaN
2881,L,KOLKATA,NaN,NaN,1 R N MUKHERJEE ROAD,M/S MARTIN BURN LTD,700001,MARTIN BURN,NaN,0103600100,NaN
2882,L,KOLKATA,NaN,NaN,"9/1.R.N.MUKHERJEE ROAD,",M/S.BIRLA BUILDING LTD.,700001,BIRLA BLDG.,NaN,0103600200,NaN
2883,L,KING SARANI,(FORMERLY WOOD STREET),KOLKATA,"9B,DR.MARTIN LUTHER",M/S J D JONES & CO P LTD,700016,J.D. JONES,NaN,0107800900,WEST BENGAL
2884,L,24 & 26 HEMANTA BASU,SARANI,KOLKATA,DEVELOPMENT FINANCE LTD,M/S MANGALAM HOUSING,700001,MANGALAM HOUSING DEVPT,FINANCE LTD,0103501301,NaN

In [9]:
temp_df.to_csv('D:/ht-cons.csv', index=False)

In [2]:
import oracledb

d = r'C:\Users\met.officer4\Downloads\instantclient-basic-windows.x64-21.13.0.0.0dbru\instantclient_21_13'
oracledb.init_oracle_client(d)
DB_URL = "safetd/safetd@//itsc-c2-scan:1521/SCTDDB"

In [3]:
connection = oracledb.connect(DB_URL)

In [4]:
df = pd.DataFrame()

In [6]:
cursor = connection.cursor()
cursor.execute("SELECT * FROM HTMETER.SINFO ORDER BY SNAME")

In [31]:
batch = cursor.fetchall()
df_batch = pd.DataFrame(batch, columns=[col[0] for col in cursor.description])
df = pd.concat([df, df_batch], ignore_index=True)

In [33]:
df.to_csv('D:/dtrList.csv', index=False)

In [32]:
df

,SCODE,SNAME,ADD1,ADD2,STATUS,KVA_RATING,CTR_PRI,CTR_SEC,REMARKS
0,0650400,2ND VIVEKANANDA BRIDGE (BALLY) O/T,None,None,None,315,600,5,None
1,0552000,2ND VIVEKANANDA BRIDGE O/T-1,None,None,None,None,600,5,Y
2,0552100,2ND VIVEKANANDA BRIDGE O/T-2,None,None,None,315,600,5,None
3,1600008,A C PAUL ST (W) O/T,None,None,None,315,600,5,None
4,03P0003,A J C BOSE RD PSS,None,None,None,990,2000,5,None
...,...,...,...,...,...,...,...,...,...
9638,0708500,ZAMINDAR RD P/T,None,None,None,300,600,5,None
9639,0639600,ZED. ROAD O/T,None,None,None,400,600,5,None
9640,0333100,ZEERUT BRIDGE T/H,None,None,None,315,600,5,None
9641,0200161,ZOOLOGICAL GARDENS ( N ) O/T,None,None,None,315,600,5,None
9642,0217300,ZOOLOGICAL GARDENS O/T,None,None,None,315,600,5,None

In [7]:
cursor.execute("SELECT * FROM TD_AMR.FDR_AUD_MATRIX")

DatabaseError: ORA-01031: insufficient privileges

In [8]:
df_aud = pd.DataFrame()

In [9]:
batch_aud = cursor.fetchall()
df_batch = pd.DataFrame(batch_aud, columns=[col[0] for col in cursor.description])
df_aud = pd.concat([df_aud, df_batch], ignore_index=True)

In [10]:
df_aud

,STATION,FEEDER_CODE,FEEDER_NAME,CHILD_CODE,CHILD_TYPE,DT1,DT2
0,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1616200,D,2024-07-01,2024-07-08
1,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1616300,D,2024-07-01,2024-07-08
2,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1629800,D,2024-07-01,2024-07-08
3,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1624100,D,2024-07-01,2024-07-08
4,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1607400,D,2024-07-01,2024-07-08
5,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1616700,D,2024-07-01,2024-07-08
6,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1619800,D,2024-07-01,2024-07-08
7,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1600147,D,2024-07-01,2024-07-08
8,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1600038,D,2024-07-01,2024-07-08
9,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1607500,D,2024-07-01,2024-07-08
10,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,1616400,D,2024-07-01,2024-07-08
11,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,0100600600,H,2024-07-01,2024-07-08
12,BARRACKPORE,21203,F.BARRACKPORE D/S OT NO.1,0100600602,H,2024-07-01,2024-07-08
13,RAJA SANTOSH,70502,F.ABB RMU AT ALIPORE PARK RD T/H// RP GOENKA I...,0200600,D,2024-07-01,2024-07-10
14,RAJA SANTOSH,70502,F.ABB RMU AT ALIPORE PARK RD T/H// RP GOENKA I...,0238500,D,2024-07-01,2024-07-10
15,RAJA SANTOSH,70502,F.ABB RMU AT ALIPORE PARK RD T/H// RP GOENKA I...,0213800,D,2024-07-01,2024-07-10
16,RAJA SANTOSH,70502,F.ABB RMU AT ALIPORE PARK RD T/H// RP GOENKA I...,0107400300,H,2024-07-01,2024-07-10
17,RAJA SANTOSH,70502,F.ABB RMU AT ALIPORE PARK RD T/H// RP GOENKA I...,0107302200,H,2024-07-01,2024-07-10
18,STRAND SOUTH,33924,F.HARIRAM GOYENKA ST.(E) O/T,0329600,D,2024-07-01,2024-07-10
19,STRAND SOUTH,33924,F.HARIRAM GOYENKA ST.(E) O/T,0400016,D,2024-07-01,2024-07-10
20,STRAND SOUTH,33924,F.HARIRAM GOYENKA ST.(E) O/T,0359800,D,2024-07-01,2024-07-10
21,STRAND SOUTH,33924,F.HARIRAM GOYENKA ST.(E) O/T,0109000118,H,2024-07-01,2024-07-10
22,STRAND SOUTH,33924,F.HARIRAM GOYENKA ST.(E) O/T,0103100402,H,2024-07-01,2024-07-10
23,THAKURPUKUR,66107,F.11 KV ABB RMU AT MAJHIPARA O/T //SE,0209930,D,2024-07-01,2024-07-10
24,THAKURPUKUR,66107,F.11 KV ABB RMU AT MAJHIPARA O/T //SE,0800236,D,2024-07-01,2024-07-10
25,THAKURPUKUR,66107,F.11 KV ABB RMU AT MAJHIPARA O/T //SE,0208400,D,2024-07-01,2024-07-10
26,THAKURPUKUR,66107,F.11 KV ABB RMU AT MAJHIPARA O/T //SE,0538400,D,2024-07-01,2024-07-10
27,THAKURPUKUR,66107,F.11 KV ABB RMU AT MAJHIPARA O/T //SE,0109000703,H,2024-07-01,2024-07-10
28,THAKURPUKUR,66107,F.11 KV ABB RMU AT MAJHIPARA O/T //SE,0101800600,H,2024-07-01,2024-07-10

In [11]:
connection.commit()
connection.close()

In [26]:
cursor.execute("SELECT * FROM HTMETER.SINFO")

In [27]:
df_2 = pd.DataFrame()

In [28]:
batch_2 = cursor.fetchall()
df_batch = pd.DataFrame(batch_2, columns=[col[0] for col in cursor.description])
df_2 = pd.concat([df_2, df_batch], ignore_index=True)

In [29]:
df_2.head()

,SCODE,SNAME,ADD1,ADD2,STATUS,KVA_RATING,CTR_PRI,CTR_SEC,REMARKS
0,0651430,HOWRAH HOMES P/T,None,None,None,400,600,5,None
1,0651440,SHIBPUR MOLLAPARA P/T,None,None,None,400,600,5,None
2,0651450,RAMKRISHNAPUR LANE O/T,None,None,None,500,600,5,None
3,0651470,SRIKISSEN VAKAT LANE O/T,None,None,None,400,600,5,None
4,0651480,BALLY SHANTIRAM RASTA P/T,None,None,None,400,600,5,None